# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94ff2a4ba1e88439d84d047c6152aa70e242d4635dbedae484a80bff44b0d5c4e4bfa678a9283f892f10d7e053752a7175d2c9eaa596085fe4081a0933b762e5

test:
  secret_key_base: fbec352c66422e0cc1b4e943f366d8b2f4426fba1cb6af984083a789d5890db16d680a4e62ec639009d21f24cdf7a5b7b7bce3ae9bd240419e93641e58028432

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
